package com.robot.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.QQ_NUM
     *
     * @mbg.generated
     */
    private Integer qqNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MONEY
     *
     * @mbg.generated
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATE
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.QQ_NUM
     *
     * @return the value of user.QQ_NUM
     *
     * @mbg.generated
     */
    public Integer getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.QQ_NUM
     *
     * @param qqNum the value for user.QQ_NUM
     *
     * @mbg.generated
     */
    public void setQqNum(Integer qqNum) {
        this.qqNum = qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MONEY
     *
     * @return the value of user.MONEY
     *
     * @mbg.generated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MONEY
     *
     * @param money the value for user.MONEY
     *
     * @mbg.generated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATE
     *
     * @return the value of user.STATE
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATE
     *
     * @param state the value for user.STATE
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}